baseURL = 'https://scoutsmontreal.com/'
languageCode = 'en-us'
title = 'Trinity Scouts Montreal 24th'
theme = "hugo-dpsg"

[Params]
  description = "Welcome to our scout group!" # Site description. Used in meta description
  copyright = "Trinity Montreal 24th" # Footer copyright holder, otherwise will use site title
  schema = false
  toc = false
  authorbox = false
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  indexPager = true # Show pager navigation on index page
  post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
  #mainSections = ["post", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
  #photosSections = ["photos"] # Specify section pages to show on home page and the "Recent photos" widget
  photoTag = "photos" # Specify one tag to show on home page and the "Recent photos" widget. Similar as photoSections, but with 1 tag instead of 1 or multiple sections
  dateformat = "02.01.2006" # Change the format of dates
#  customCSS = ["css/custom.css"] # Include custom CSS files, can also be used per-page as front matter attribute

[Params.style.vars]
  highlightColor = "#396a3b" # Override main theme color

[Params.logo]
  image = "img/trinity-rosemount-24th-montreal-scout-group.png" # Logo image. Path relative to "static"
  image_alt = "Trinity Scouts Logo" # alt text for logo image, be screen reader friendly!
  header = "img/header.jpg" # Header image. Path relative to "static"
  title = "Trinity Scouts" # Logo title, otherwise will use site title
  subtitle = "Montreal 24th" # Logo subtitle

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "recent_photos", "recent_photos_tags", "categories", "taglist", "social", "languages"]
  

[Params.widgets.social]
  # Enable parts of social widget
  facebook = "groups/24thMontrealScoutGroup/"
  email = "montrealscouts.ca@gmail.com"

[[module.mounts]]
source = 'static'
target = 'static'